# Welcome to Jekyll!
#

# Site settings
title: Sidimar Gobbo
description: |
  UX / UI Desinger
owner: Sidimar # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: sidiamr@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sidimar.com" # the base hostname & protocol for your site
social:
  behance: https://www.behance.net/sidimar
  twitter: https://twitter.com/sidimar
  github: https://github.com/sidimar
  linkedin-square: https://linkedin.com/in/sidimar
  facebook-official: https://facebook.com/sidimar
  google-plus-square: https://plus.google.com/u/0/+SidimarGobbo
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
